general:
  data_dir: '/home/jojo/Documents/textworld/sample_games/' #location of game data

writing:
  extension: '' #name to save as
  save_dir: './saves/' #directory to save in
  save_freq: 10 #episodes before saving
  log_dir: './logs/' #directory to log in
  log_freq: 10 #episodes before logging

vocab:
  size: 20200 #unique words/chars in dataset

replay:
  cap: 20000 #max transitions in replay memory

train:
  learning_rate: 0.001 #gradient step size
  batch_size: 1
  epochs: 100 #episodes
  max_steps: 10  #episode ends after 50 actions
  optim: 'adam'

model:
  embedding_size: 64 #of each word vector (4th root = 12), neurons in GRU
  units: 1024 #number of neurons in gru
