#****************
# General Params 
#****************
data_dir: '/home/jojo/Documents/textworld/sample_games/' #location of game data
seed: 1 #default random seed
env: 'Pendulum-v0' #gym control environment, options=['Pendulum-v0', 'MountainCarContinuous-v0', 'Ant-v2', 'HalfCheetah-v2', 'Hopper-v2', 'Humanoid-v2', 'HumanoidStandup-v2', 'InvertedDoublePendulum-v2', 'InvertedPendulum-v2', 'Reacher-v2', 'Swimmer-v2', 'Walker2d-v2']
render: true #render environment

#**************
# Model Params
#**************
embedding_size: 1024
hidden_size: 200
belief_size: 200
state_size: 30
activ: 'relu'
min_std_dev: 0.1

#**************
# Vocab Params
#**************
size: 20200 #unique words/chars in dataset

#***************
# Replay Params
#***************
cap: 100000 #max experiences in replay memory
seed_episodes: 5 #episodes to init memory with
 
#************
# I/O Params 
#************
id: '' #name to save as
save_dir: './saves/' #directory to save in
save_freq: 50 #episodes before saving
log_dir: './logs/' #directory to log in
log_freq: 1 #episodes before logging

#**************
# Train Params
#**************
batch_size: 50
chunk_size: 50
learning_rate: 0.001 #1e-3
lr_schedule: false #learning rate schedule
optim: 'adam'
optim_eps: 0.0001 #epsilon
grad_clip: 1000 #gradient clipping norm
planning_horizon: 12 #planning horizon distance
planning_opt_iters: 10
candidates: 1000 #candidate samples per iteration
top_candidates: 100 #number of top candidates to fit
skiprate: 2
action_noise: 0.3
collect_interval: 100
overshooting_dist: 50 #latent overshooting distance for t=1
overshooting_kl_beta: 0 #latent overshooting KL weight for t > 1
overshooting_reward_scale: 0 #latent overshooting reward prediction weight for t > 1
global_kl_beta: 0
free_nats: 3
bit_depth: 5 #image bit depth (quantisation)
max_steps: 1000

train:
  episodes: 1000 #epochs

#*************
# Test Params
#*************
interval: 25

test:
  episodes: 10
